services:
  product-service:
    build:
      context: ./product-service
    ports:
      - "8081:8080"
    depends_on:
      - mongo

  order-service:
    build:
      context: ./order-service
    ports:
      - "8082:8080"
    depends_on:
      - mongo
      - product-service

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
